server:
  port: 9001
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_classmanager?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zht12345678@
    druid:
      initial-size: 10
      min-idle: 5
      max-active: 20
      max-wait: 6000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: zht12345678@
        allow: 127.0.0.1
  data:
    redis:
      jedis:
        pool:
          enabled: true
      host: 192.168.116.200
      port: 6379
      password: 123456
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  charset:
    console: GBK


